export const AuditAction = {
  CONTENT_APPROVED: 'CONTENT_APPROVED',
  CONTENT_ARCHIVED: 'CONTENT_ARCHIVED',
  CONTENT_CREATED: 'CONTENT_CREATED',
  CONTENT_EDITED: 'CONTENT_EDITED',
  CONTENT_REJECTED: 'CONTENT_REJECTED',
  CONTENT_REVISED: 'CONTENT_REVISED',
  CONTENT_SUBMITTED_FOR_REVIEW: 'CONTENT_SUBMITTED_FOR_REVIEW',
} as const;

export const AuditEntityType = {
  CONTENT: 'CONTENT',
} as const;
