export const AuditAction = {
  CONTENT_APPROVED: 'CONTENT_APPROVED',
  CONTENT_ARCHIVED: 'CONTENT_ARCHIVED',
  CONTENT_CREATED: 'CONTENT_CREATED',
  CONTENT_EDITED: 'CONTENT_EDITED',
  CONTENT_REJECTED: 'CONTENT_REJECTED',
  CONTENT_REVISED: 'CONTENT_REVISED',
  CONTENT_SUBMITTED_FOR_REVIEW: 'CONTENT_SUBMITTED_FOR_REVIEW',
  SLACK_TEST_MESSAGE_SENT: 'SLACK_TEST_MESSAGE_SENT',
  SUBSCRIBER_CREATED: 'SUBSCRIBER_CREATED',
  SUBSCRIBER_UPDATED: 'SUBSCRIBER_UPDATED',
  WORKSPACE_CREATED: 'WORKSPACE_CREATED',
  WORKSPACE_TOKEN_VERIFIED: 'WORKSPACE_TOKEN_VERIFIED',
  WORKSPACE_UPDATED: 'WORKSPACE_UPDATED',
} as const;

export const AuditEntityType = {
  CONTENT: 'CONTENT',
  SUBSCRIBER: 'SUBSCRIBER',
  WORKSPACE: 'WORKSPACE',
} as const;
