export interface SurahName {
  arabic: string;
  english: string;
}

/**
 * Static Mushaf metadata — surah names never change, so this avoids a live `/chapters` call on
 * every import (same reasoning as the hardcoded `SURAH_AYAH_COUNTS` in
 * `content-validation.service.ts`, which this table is indexed identically to: index 0 is surah
 * 1 (Al-Fatihah), index 113 is surah 114 (An-Nas).
 */
export const SURAH_NAMES: readonly SurahName[] = [
  { arabic: 'الفاتحة', english: 'Al-Fatihah' },
  { arabic: 'البقرة', english: 'Al-Baqarah' },
  { arabic: 'آل عمران', english: 'Aali Imran' },
  { arabic: 'النساء', english: 'An-Nisa' },
  { arabic: 'المائدة', english: "Al-Ma'idah" },
  { arabic: 'الأنعام', english: "Al-An'am" },
  { arabic: 'الأعراف', english: "Al-A'raf" },
  { arabic: 'الأنفال', english: 'Al-Anfal' },
  { arabic: 'التوبة', english: 'At-Tawbah' },
  { arabic: 'يونس', english: 'Yunus' },
  { arabic: 'هود', english: 'Hud' },
  { arabic: 'يوسف', english: 'Yusuf' },
  { arabic: 'الرعد', english: "Ar-Ra'd" },
  { arabic: 'إبراهيم', english: 'Ibrahim' },
  { arabic: 'الحجر', english: 'Al-Hijr' },
  { arabic: 'النحل', english: 'An-Nahl' },
  { arabic: 'الإسراء', english: 'Al-Isra' },
  { arabic: 'الكهف', english: 'Al-Kahf' },
  { arabic: 'مريم', english: 'Maryam' },
  { arabic: 'طه', english: 'Ta-Ha' },
  { arabic: 'الأنبياء', english: 'Al-Anbiya' },
  { arabic: 'الحج', english: 'Al-Hajj' },
  { arabic: 'المؤمنون', english: "Al-Mu'minun" },
  { arabic: 'النور', english: 'An-Nur' },
  { arabic: 'الفرقان', english: 'Al-Furqan' },
  { arabic: 'الشعراء', english: "Ash-Shu'ara" },
  { arabic: 'النمل', english: 'An-Naml' },
  { arabic: 'القصص', english: 'Al-Qasas' },
  { arabic: 'العنكبوت', english: 'Al-Ankabut' },
  { arabic: 'الروم', english: 'Ar-Rum' },
  { arabic: 'لقمان', english: 'Luqman' },
  { arabic: 'السجدة', english: 'As-Sajdah' },
  { arabic: 'الأحزاب', english: 'Al-Ahzab' },
  { arabic: 'سبأ', english: 'Saba' },
  { arabic: 'فاطر', english: 'Fatir' },
  { arabic: 'يس', english: 'Ya-Sin' },
  { arabic: 'الصافات', english: 'As-Saffat' },
  { arabic: 'ص', english: 'Sad' },
  { arabic: 'الزمر', english: 'Az-Zumar' },
  { arabic: 'غافر', english: 'Ghafir' },
  { arabic: 'فصلت', english: 'Fussilat' },
  { arabic: 'الشورى', english: 'Ash-Shuraa' },
  { arabic: 'الزخرف', english: 'Az-Zukhruf' },
  { arabic: 'الدخان', english: 'Ad-Dukhan' },
  { arabic: 'الجاثية', english: 'Al-Jathiyah' },
  { arabic: 'الأحقاف', english: 'Al-Ahqaf' },
  { arabic: 'محمد', english: 'Muhammad' },
  { arabic: 'الفتح', english: 'Al-Fath' },
  { arabic: 'الحجرات', english: 'Al-Hujurat' },
  { arabic: 'ق', english: 'Qaf' },
  { arabic: 'الذاريات', english: 'Adh-Dhariyat' },
  { arabic: 'الطور', english: 'At-Tur' },
  { arabic: 'النجم', english: 'An-Najm' },
  { arabic: 'القمر', english: 'Al-Qamar' },
  { arabic: 'الرحمن', english: 'Ar-Rahman' },
  { arabic: 'الواقعة', english: "Al-Waqi'ah" },
  { arabic: 'الحديد', english: 'Al-Hadid' },
  { arabic: 'المجادلة', english: 'Al-Mujadila' },
  { arabic: 'الحشر', english: 'Al-Hashr' },
  { arabic: 'الممتحنة', english: 'Al-Mumtahanah' },
  { arabic: 'الصف', english: 'As-Saff' },
  { arabic: 'الجمعة', english: "Al-Jumu'ah" },
  { arabic: 'المنافقون', english: 'Al-Munafiqun' },
  { arabic: 'التغابن', english: 'At-Taghabun' },
  { arabic: 'الطلاق', english: 'At-Talaq' },
  { arabic: 'التحريم', english: 'At-Tahrim' },
  { arabic: 'الملك', english: 'Al-Mulk' },
  { arabic: 'القلم', english: 'Al-Qalam' },
  { arabic: 'الحاقة', english: 'Al-Haqqah' },
  { arabic: 'المعارج', english: "Al-Ma'arij" },
  { arabic: 'نوح', english: 'Nuh' },
  { arabic: 'الجن', english: 'Al-Jinn' },
  { arabic: 'المزمل', english: 'Al-Muzzammil' },
  { arabic: 'المدثر', english: 'Al-Muddaththir' },
  { arabic: 'القيامة', english: 'Al-Qiyamah' },
  { arabic: 'الإنسان', english: 'Al-Insan' },
  { arabic: 'المرسلات', english: 'Al-Mursalat' },
  { arabic: 'النبأ', english: 'An-Naba' },
  { arabic: 'النازعات', english: "An-Nazi'at" },
  { arabic: 'عبس', english: 'Abasa' },
  { arabic: 'التكوير', english: 'At-Takwir' },
  { arabic: 'الانفطار', english: 'Al-Infitar' },
  { arabic: 'المطففين', english: 'Al-Mutaffifin' },
  { arabic: 'الانشقاق', english: 'Al-Inshiqaq' },
  { arabic: 'البروج', english: 'Al-Buruj' },
  { arabic: 'الطارق', english: 'At-Tariq' },
  { arabic: 'الأعلى', english: "Al-A'la" },
  { arabic: 'الغاشية', english: 'Al-Ghashiyah' },
  { arabic: 'الفجر', english: 'Al-Fajr' },
  { arabic: 'البلد', english: 'Al-Balad' },
  { arabic: 'الشمس', english: 'Ash-Shams' },
  { arabic: 'الليل', english: 'Al-Layl' },
  { arabic: 'الضحى', english: 'Ad-Duhaa' },
  { arabic: 'الشرح', english: 'Ash-Sharh' },
  { arabic: 'التين', english: 'At-Tin' },
  { arabic: 'العلق', english: 'Al-Alaq' },
  { arabic: 'القدر', english: 'Al-Qadr' },
  { arabic: 'البينة', english: 'Al-Bayyinah' },
  { arabic: 'الزلزلة', english: 'Az-Zalzalah' },
  { arabic: 'العاديات', english: 'Al-Adiyat' },
  { arabic: 'القارعة', english: "Al-Qari'ah" },
  { arabic: 'التكاثر', english: 'At-Takathur' },
  { arabic: 'العصر', english: 'Al-Asr' },
  { arabic: 'الهمزة', english: 'Al-Humazah' },
  { arabic: 'الفيل', english: 'Al-Fil' },
  { arabic: 'قريش', english: 'Quraysh' },
  { arabic: 'الماعون', english: "Al-Ma'un" },
  { arabic: 'الكوثر', english: 'Al-Kawthar' },
  { arabic: 'الكافرون', english: 'Al-Kafirun' },
  { arabic: 'النصر', english: 'An-Nasr' },
  { arabic: 'المسد', english: 'Al-Masad' },
  { arabic: 'الإخلاص', english: 'Al-Ikhlas' },
  { arabic: 'الفلق', english: 'Al-Falaq' },
  { arabic: 'الناس', english: 'An-Nas' },
] as const;
